def parts(x):
    if x == 0:
        print('     ',  '------')
        print('     ',  '|    |')
        print('     ',  '|     ')
        print('     ',  '|     ')
        print('     ',  '|     ')
        print('     ',  '|     ')
        print('----------------------')
    if x ==1:
        print('     ',  '------')
        print('     ',  '|    |')
        print('     ',  '|    O')
        print('     ',  '|     ')
        print('     ',  '|     ')
        print('     ',  '|     ')
        print('----------------------')
    if x == 2:
        print('     ',  '------')
        print('     ',  '|    |')
        print('     ',  '|    O')
        print('     ',  '|   / ')
        print('     ',  '|     ')
        print('     ',  '|     ')        
        print('----------------------')
    if x == 3:
        print('     ',  '------')
        print('     ',  '|    |')
        print('     ',  '|    O')
        print('     ',  '|   / \\')
        print('     ',  '|     ')
        print('     ',  '|     ')        
        print('----------------------')
    if x == 4:
        print('     ',  '------')
        print('     ',  '|    |')
        print('     ',  '|    O')
        print('     ',  '|   /|\\')
        print('     ',  '|     ')
        print('     ',  '|     ')        
        print('----------------------')
    if x == 5:
        print('     ',  '------')
        print('     ',  '|    |')
        print('     ',  '|    O')
        print('     ',  '|   /|\\')
        print('     ',  '|    |')
        print('     ',  '|     ')        
        print('----------------------')


    if x == 6:
        print('     ',  '------')
        print('     ',  '|    |')
        print('     ',  '|    O')
        print('     ',  '|   /|\\')
        print('     ',  '|    | ')
        print('     ',  '|   / ')
        print('-------------')
    if x ==7:
        print('     ',  '------')
        print('     ',  '|    |')
        print('     ',  '|    O')
        print('     ',  '|   /|\\')
        print('     ',  '|    | ')
        print('     ',  '|   / \\')
        print('--------------')